#!/bin/bash
git fetch
git pull

echo 'Write the name of the fules to send (defaul:all)'
read -e -p "files to send: " archives_to_push
git add $archives_to_push
read -e -p "message fot this commit: " message
git commit -m "$message"

echo 'files deleted: '
files_deleted= git status -s | grep 'D' | awk '{print $2}' | paste -s
echo 'files added: '
files_added= git status -s | grep 'A' | awk '{print $2}' | paste -s
echo 'files unknown: '
files_u= git status -s | grep '??' | awk '{print $2}' | paste -s




user_name= git config user.name > /dev/null 2>&1
user_email= git config user.email > /dev/null 2>&1

if [[ $? -eq 2 ]];then
	echo 'User name or email is not set'
	read -e -p "Please write your user name of github for config: " $user_name
	read -e -p "Please write your user email of github for config: " $user_email
	git config user.name "$user_name"
	git config user.email "$user_email"
fi


read -e -p "You are sure to push this files?[Y/n]" $response

if [[ $response -eq "n" ]];then
	timeout 1
else echo hola 2
fi

git push
