#!/bin/bash

echo -e "jgit by (jgnacio)\ncheck the repo..."
git fetch
git pull

echo '==== Git status ===='
echo 'Files Modified: '
files_deleted= git status -s | grep 'M' | awk '{print $2}' | paste -s
echo 'Files deleted: '
files_deleted= git status -s | grep 'D' | awk '{print $2}' | paste -s
echo 'Files added: '
files_added= git status -s | grep 'A' | awk '{print $2}' | paste -s
echo 'Files unknown: '
files_u= git status -s | grep '??' | awk '{print $2}' | paste -s
echo '===================='

#echo 'Write the name of the fules to send (defaul:all)'
read -e -p "files to send: " archives_to_push
git add $archives_to_push
read -e -p "message fot this commit: " message
git commit -m "$message"

#config for the user
user_name= git config user.name > /dev/null 2>&1
user_email= git config user.email > /dev/null 2>&1

if [[ $? -eq 2 ]];then
	echo 'User name or email is not set'
	read -e -p "Please write your user name of github for config: " $user_name
	read -e -p "Please write your user email of github for config: " $user_email
	git config user.name "$user_name"
	git config user.email "$user_email"
fi


read -e -p "Are you sure to push this files?[Y/n]" response
if [[ $response != "y" && $response != "" ]];then
	echo exit
	kill $PPID
else
git push
fi
